version: '3.9'


services:
  cloud_gate:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: cloud_gate
    restart: always
    env_file:
      - ./.env
    expose:
      - ${SERVICE_PORT}
    logging:
      options:
        max-size: 50m

  cloud_nginx:
    container_name: cloud_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - ${NGINX_PORT}:8080
    env_file:
      - ./.env
    depends_on:
      - cloud_gate