volumes:
  billing-manager-postgres_data:
  billing-manager-redis_data:


services:
  billing-manager-web:
    platform: linux/amd64
    build: .
    command: sh /code/entrypoint.sh
    env_file:
      - ./.env
    volumes:
      - .:/code
    depends_on:
      - billing-manager-db

  billing-manager-nginx:
    platform: linux/amd64
    image: nginx:1.19.2
    depends_on:
      - billing-manager-web
      - billing-manager-db
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static

  billing-manager-celery:
    platform: linux/amd64
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - billing-manager-web
      - billing-manager-redis

  billing-manager-celery-beat:
    platform: linux/amd64
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - billing-manager-web
      - billing-manager-redis

  billing-manager-redis:
    platform: linux/amd64
    image: redis:6.2.6-alpine
    volumes:
      - billing-manager-redis_data:/var/lib/redis/data

  billing-manager-db:
    platform: linux/amd64
    image: postgres:14
    volumes:
      - billing-manager-postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
